// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
// NOTE: Next.js `next build` type-checks this file, but `prisma/config` is not
// currently exposed as a TS module in our installed Prisma version.
// Keep this file JS/TS-simple to avoid breaking builds.

export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || 'file:./dev.db',
  },
} as const;
