export const STABLE_ERROR = {
  UNAUTHORIZED_ROLE: 'UNAUTHORIZED_ROLE',
  INVALID_TARGET: 'INVALID_TARGET',
  TARGET_SCOPE_VIOLATION: 'TARGET_SCOPE_VIOLATION',
  ANNOUNCEMENT_NOT_FOUND: 'ANNOUNCEMENT_NOT_FOUND',

  // Finance (S01)
  FINANCE_FORBIDDEN: 'FINANCE_FORBIDDEN',
  FINANCE_INVALID_PERIOD_KEY: 'FINANCE_INVALID_PERIOD_KEY',
  FINANCE_CONCEPT_NOT_FOUND: 'FINANCE_CONCEPT_NOT_FOUND',
  FINANCE_SCOPE_VIOLATION: 'FINANCE_SCOPE_VIOLATION',

  // Finance (S02)
  FINANCE_CHARGE_NOT_FOUND: 'FINANCE_CHARGE_NOT_FOUND',
  FINANCE_PAYMENT_INVALID_AMOUNT: 'FINANCE_PAYMENT_INVALID_AMOUNT',

  // Finance (M010 - discounts / payment plans)
  FINANCE_DISCOUNT_NOT_FOUND: 'FINANCE_DISCOUNT_NOT_FOUND',
  FINANCE_DISCOUNT_INVALID_RULE: 'FINANCE_DISCOUNT_INVALID_RULE',
  FINANCE_PLAN_NOT_FOUND: 'FINANCE_PLAN_NOT_FOUND',
  FINANCE_PLAN_INVALID: 'FINANCE_PLAN_INVALID',
  FINANCE_PLAN_ALREADY_EXISTS: 'FINANCE_PLAN_ALREADY_EXISTS',

  // Calendar (M005/S01)
  CALENDAR_FORBIDDEN: 'CALENDAR_FORBIDDEN',
  CALENDAR_EVENT_NOT_FOUND: 'CALENDAR_EVENT_NOT_FOUND',

  // Invitations / registration
  INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  INVITE_USED: 'INVITE_USED',
  INVITE_TARGET_NOT_FOUND: 'INVITE_TARGET_NOT_FOUND',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
} as const;

export type StableErrorCode = (typeof STABLE_ERROR)[keyof typeof STABLE_ERROR];

export function stableError(code: StableErrorCode): Error {
  return new Error(code);
}
