export const STABLE_ERROR = {
  UNAUTHORIZED_ROLE: 'UNAUTHORIZED_ROLE',
  INVALID_TARGET: 'INVALID_TARGET',
  TARGET_SCOPE_VIOLATION: 'TARGET_SCOPE_VIOLATION',
  ANNOUNCEMENT_NOT_FOUND: 'ANNOUNCEMENT_NOT_FOUND',

  // Finance (S01)
  FINANCE_FORBIDDEN: 'FINANCE_FORBIDDEN',
  FINANCE_INVALID_PERIOD_KEY: 'FINANCE_INVALID_PERIOD_KEY',
  FINANCE_CONCEPT_NOT_FOUND: 'FINANCE_CONCEPT_NOT_FOUND',
  FINANCE_SCOPE_VIOLATION: 'FINANCE_SCOPE_VIOLATION',

  // Finance (S02)
  FINANCE_CHARGE_NOT_FOUND: 'FINANCE_CHARGE_NOT_FOUND',
  FINANCE_PAYMENT_INVALID_AMOUNT: 'FINANCE_PAYMENT_INVALID_AMOUNT',

  // Finance (M010 - discounts / payment plans)
  FINANCE_DISCOUNT_NOT_FOUND: 'FINANCE_DISCOUNT_NOT_FOUND',
  FINANCE_DISCOUNT_INVALID_RULE: 'FINANCE_DISCOUNT_INVALID_RULE',
  FINANCE_PLAN_NOT_FOUND: 'FINANCE_PLAN_NOT_FOUND',
  FINANCE_PLAN_INVALID: 'FINANCE_PLAN_INVALID',
  FINANCE_PLAN_ALREADY_EXISTS: 'FINANCE_PLAN_ALREADY_EXISTS',

  // Calendar (M005/S01)
  CALENDAR_FORBIDDEN: 'CALENDAR_FORBIDDEN',
  CALENDAR_EVENT_NOT_FOUND: 'CALENDAR_EVENT_NOT_FOUND',

  // Invitations / registration
  INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  INVITE_USED: 'INVITE_USED',
  INVITE_TARGET_NOT_FOUND: 'INVITE_TARGET_NOT_FOUND',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',

  // Assignments / submissions
  ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',
  SUBMISSION_FORBIDDEN: 'SUBMISSION_FORBIDDEN',

  // Password reset
  RESET_TOKEN_NOT_FOUND: 'RESET_TOKEN_NOT_FOUND',
  RESET_TOKEN_USED: 'RESET_TOKEN_USED',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',

  // Admissions
  APPLICANT_NOT_FOUND: 'APPLICANT_NOT_FOUND',
  APPLICANT_ALREADY_CONVERTED: 'APPLICANT_ALREADY_CONVERTED',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',

  // Certificates
  ENROLLMENT_NOT_FOUND: 'ENROLLMENT_NOT_FOUND',

  // Conduct
  CONDUCT_FORBIDDEN: 'CONDUCT_FORBIDDEN',
  CONDUCT_RECORD_NOT_FOUND: 'CONDUCT_RECORD_NOT_FOUND',

  // Library
  BOOK_NOT_FOUND: 'BOOK_NOT_FOUND',
  BOOK_NOT_AVAILABLE: 'BOOK_NOT_AVAILABLE',
  BOOK_HAS_ACTIVE_LOANS: 'BOOK_HAS_ACTIVE_LOANS',
  LOAN_NOT_FOUND: 'LOAN_NOT_FOUND',
  LOAN_ALREADY_RETURNED: 'LOAN_ALREADY_RETURNED',

  // Transport
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  ROUTE_HAS_ASSIGNMENTS: 'ROUTE_HAS_ASSIGNMENTS',
  ROUTE_FULL: 'ROUTE_FULL',
  STOP_NOT_FOUND: 'STOP_NOT_FOUND',

  // Cafeteria
  MENU_ITEM_NOT_FOUND: 'MENU_ITEM_NOT_FOUND',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',

  // Health
  HEALTH_FORBIDDEN: 'HEALTH_FORBIDDEN',

  // HR / Payroll
  HR_FORBIDDEN: 'HR_FORBIDDEN',
  CONTRACT_NOT_FOUND: 'CONTRACT_NOT_FOUND',
  PAYROLL_PERIOD_NOT_FOUND: 'PAYROLL_PERIOD_NOT_FOUND',
  PAYROLL_ENTRY_EXISTS: 'PAYROLL_ENTRY_EXISTS',
  PAYROLL_ENTRY_NOT_FOUND: 'PAYROLL_ENTRY_NOT_FOUND',
} as const;

export type StableErrorCode = (typeof STABLE_ERROR)[keyof typeof STABLE_ERROR];

export function stableError(code: StableErrorCode): Error {
  return new Error(code);
}
